import type { CharacterDefinition } from './hero';
import { buildFighterCharacter, rect, type FighterActionSpec } from './fighterCharacter';

// Generated by scripts/sprites/character.py from scripts/sprites/characters/asura-blade.json.
// defaultVisual comes from the packed sheets, width-capped so the hurtbox follows the
// body rather than the weapon (visualWidthCap / visualFrom in the manifest). Attack boxes
// are measured from what sticks out in front of the body on the strike frames; guard
// boxes are copied from the shipped fighters. Tune by hand after playtesting.

export const ASURA_BLADE_CHARACTER_ID = 'asura-blade';

const ASURA_BLADE_ACTIONS: FighterActionSpec[] = [
  {
    action: 'idle',
    label: 'Idle',
    file: 'idle.png',
    frames: 6,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(161, 27, 120, 202)
  },
  {
    action: 'walk-forward',
    label: 'Walk Forward',
    file: 'walk-forward.png',
    frames: 6,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(161, 31, 120, 198)
  },
  {
    action: 'walk-backward',
    label: 'Walk Backward',
    file: 'walk-backward.png',
    frames: 6,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(161, 31, 120, 198)
  },
  {
    action: 'crouch',
    label: 'Crouch',
    file: 'crouch.png',
    frames: 6,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(161, 57, 120, 172)
  },
  {
    action: 'jump',
    label: 'Jump',
    file: 'jump.png',
    frames: 6,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(161, 27, 120, 202)
  },
  {
    action: 'block-high',
    label: 'Block High',
    file: 'block-high.png',
    frames: 6,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(161, 30, 120, 199),
    guard: rect(156, 44, 136, 116)
  },
  {
    action: 'block-low',
    label: 'Block Low',
    file: 'block-low.png',
    frames: 6,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(161, 65, 120, 163),
    guard: rect(156, 110, 136, 120)
  },
  {
    action: 'hit-high',
    label: 'Hit High',
    file: 'hit-high.png',
    frames: 4,
    frameRate: 12,
    repeat: 0,
    defaultVisual: rect(161, 32, 120, 197)
  },
  {
    action: 'light-punch',
    label: 'Twin Fang',
    file: 'light-punch.png',
    frames: 6,
    frameRate: 14,
    repeat: 0,
    defaultVisual: rect(141, 29, 160, 199),
    attack: { frames: [2, 3], bounds: rect(86, 43, 63, 112) }
  },
  {
    action: 'heavy-kick',
    label: 'Ground Rend',
    file: 'heavy-kick.png',
    frames: 6,
    frameRate: 12,
    repeat: 0,
    defaultVisual: rect(136, 28, 170, 201),
    attack: { frames: [2, 3], bounds: rect(101, 94, 43, 128) }
  },
  {
    action: 'special-charge',
    label: 'Asura Awakening',
    file: 'special-charge.png',
    frames: 6,
    frameRate: 14,
    repeat: 0,
    defaultVisual: rect(161, 25, 120, 203)
  },
  {
    action: 'special',
    label: 'Asura Twin Crescent',
    file: 'special.png',
    frames: 9,
    frameRate: 16,
    repeat: 0,
    defaultVisual: rect(126, 23, 190, 206)
  },
  {
    action: 'knockdown',
    label: 'Knockdown',
    file: 'knockdown.png',
    frames: 6,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(133, 152, 176, 84)
  }
];

export const ASURA_BLADE_CHARACTER: CharacterDefinition = buildFighterCharacter({
  id: ASURA_BLADE_CHARACTER_ID,
  label: 'Asura Blade',
  assetRoot: '/assets/asura-blade',
  anchorUsage: 'asura-blade west-facing high-fidelity anchor',
  frameWidth: 448,
  actions: ASURA_BLADE_ACTIONS
});
