import type { CharacterDefinition } from './hero';
import { buildFighterCharacter, rect, type FighterActionSpec } from './fighterCharacter';

// Generated by scripts/sprites/character.py from scripts/sprites/characters/hac-long.json.
// defaultVisual comes from the packed sheets, width-capped so the hurtbox follows the
// body rather than the weapon (visualWidthCap / visualFrom in the manifest). Attack boxes
// are measured from what sticks out in front of the body on the strike frames; guard
// boxes are copied from the shipped fighters. Tune by hand after playtesting.

export const HAC_LONG_CHARACTER_ID = 'hac-long';

const HAC_LONG_ACTIONS: FighterActionSpec[] = [
  {
    action: 'idle',
    label: 'Idle',
    file: 'idle.png',
    frames: 6,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(129, 24, 120, 204)
  },
  {
    action: 'walk-forward',
    label: 'Walk Forward',
    file: 'walk-forward.png',
    frames: 7,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(129, 30, 120, 198)
  },
  {
    action: 'walk-backward',
    label: 'Walk Backward',
    file: 'walk-backward.png',
    frames: 8,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(129, 38, 120, 190)
  },
  {
    action: 'crouch',
    label: 'Crouch',
    file: 'crouch.png',
    frames: 8,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(129, 57, 120, 171)
  },
  {
    action: 'jump',
    label: 'Jump',
    file: 'jump.png',
    frames: 5,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(129, 20, 120, 208)
  },
  {
    action: 'block-high',
    label: 'Block High',
    file: 'block-high.png',
    frames: 7,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(129, 23, 120, 205),
    guard: rect(124, 44, 136, 116)
  },
  {
    action: 'block-low',
    label: 'Block Low',
    file: 'block-low.png',
    frames: 7,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(129, 66, 120, 162),
    guard: rect(124, 110, 136, 120)
  },
  {
    action: 'hit-high',
    label: 'Hit High',
    file: 'hit-high.png',
    frames: 4,
    frameRate: 12,
    repeat: 0,
    defaultVisual: rect(129, 34, 120, 194)
  },
  {
    action: 'light-punch',
    label: 'Dragon Claw',
    file: 'light-punch.png',
    frames: 6,
    frameRate: 14,
    repeat: 0,
    defaultVisual: rect(119, 32, 140, 196),
    attack: { frames: [2, 3], bounds: rect(104, 68, 64, 40) }
  },
  {
    action: 'heavy-kick',
    label: 'Dragon Tail',
    file: 'heavy-kick.png',
    frames: 6,
    frameRate: 12,
    repeat: 0,
    defaultVisual: rect(109, 24, 160, 205),
    attack: { frames: [2, 3], bounds: rect(46, 153, 71, 46) }
  },
  {
    action: 'special-charge',
    label: 'Dragon Awakens',
    file: 'special-charge.png',
    frames: 7,
    frameRate: 14,
    repeat: 0,
    defaultVisual: rect(129, 18, 120, 210)
  },
  {
    action: 'special',
    label: 'Dragon\'s Regret',
    file: 'special.png',
    frames: 9,
    frameRate: 16,
    repeat: 0,
    defaultVisual: rect(99, 16, 180, 212),
    attackSpans: [
      { frames: [2], bounds: rect(88, 58, 72, 50) },
      { frames: [4], bounds: rect(112, 18, 72, 90) },
      { frames: [6], bounds: rect(20, 16, 87, 123) }
    ]
  },
  {
    action: 'knockdown',
    label: 'Knockdown',
    file: 'knockdown.png',
    frames: 6,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(101, 166, 176, 62)
  }
];

export const HAC_LONG_CHARACTER: CharacterDefinition = buildFighterCharacter({
  id: HAC_LONG_CHARACTER_ID,
  label: 'Black Dragon',
  assetRoot: '/assets/hac-long',
  anchorUsage: 'hac-long west-facing high-fidelity anchor',
  frameWidth: 384,
  actions: HAC_LONG_ACTIONS
});
