import type { CharacterDefinition } from './hero';
import { buildFighterCharacter, rect, type FighterActionSpec } from './fighterCharacter';

// Generated by scripts/sprites/character.py from scripts/sprites/characters/kunoichi.json.
// defaultVisual comes from the packed sheets, width-capped so the hurtbox follows the
// body rather than the weapon (visualWidthCap / visualFrom in the manifest). Attack boxes
// are measured from what sticks out in front of the body on the strike frames; guard
// boxes are copied from the shipped fighters. Tune by hand after playtesting.

export const KUNOICHI_CHARACTER_ID = 'kunoichi';

const KUNOICHI_ACTIONS: FighterActionSpec[] = [
  {
    action: 'idle',
    label: 'Idle',
    file: 'idle.png',
    frames: 6,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(97, 25, 120, 203)
  },
  {
    action: 'walk-forward',
    label: 'Walk Forward',
    file: 'walk-forward.png',
    frames: 6,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(97, 25, 120, 203)
  },
  {
    action: 'walk-backward',
    label: 'Walk Backward',
    file: 'walk-backward.png',
    frames: 6,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(97, 25, 120, 203)
  },
  {
    action: 'crouch',
    label: 'Crouch',
    file: 'crouch.png',
    frames: 3,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(97, 61, 120, 167)
  },
  {
    action: 'jump',
    label: 'Jump',
    file: 'jump.png',
    frames: 6,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(97, 26, 120, 203)
  },
  {
    action: 'block-high',
    label: 'Block High',
    file: 'block-high.png',
    frames: 6,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(97, 26, 120, 202),
    guard: rect(92, 44, 136, 116)
  },
  {
    action: 'block-low',
    label: 'Block Low',
    file: 'block-low.png',
    frames: 3,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(97, 54, 120, 174),
    guard: rect(92, 110, 136, 120)
  },
  {
    action: 'hit-high',
    label: 'Hit High',
    file: 'hit-high.png',
    frames: 6,
    frameRate: 12,
    repeat: 0,
    defaultVisual: rect(97, 31, 120, 197)
  },
  {
    action: 'light-punch',
    label: 'Kunai Jab',
    file: 'light-punch.png',
    frames: 6,
    frameRate: 14,
    repeat: 0,
    defaultVisual: rect(87, 25, 140, 203),
    attack: { frames: [2, 3], bounds: rect(51, 54, 44, 58) }
  },
  {
    action: 'heavy-kick',
    label: 'Sweep Kick',
    file: 'heavy-kick.png',
    frames: 6,
    frameRate: 12,
    repeat: 0,
    defaultVisual: rect(77, 29, 160, 199),
    attack: { frames: [2, 3], bounds: rect(25, 59, 60, 142) }
  },
  {
    action: 'special-charge',
    label: 'Shadow Seal',
    file: 'special-charge.png',
    frames: 6,
    frameRate: 14,
    repeat: 0,
    defaultVisual: rect(97, 23, 120, 205)
  },
  {
    action: 'special',
    label: 'Shadow Flurry',
    file: 'special.png',
    frames: 9,
    frameRate: 16,
    repeat: 0,
    defaultVisual: rect(67, 40, 180, 196),
    attackSpans: [
      { frames: [2], bounds: rect(5, 83, 70, 64) },
      { frames: [4], bounds: rect(4, 83, 71, 63) },
      { frames: [6], bounds: rect(4, 44, 176, 182) }
    ]
  },
  {
    action: 'knockdown',
    label: 'Knockdown',
    file: 'knockdown.png',
    frames: 8,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(69, 140, 176, 93)
  }
];

export const KUNOICHI_CHARACTER: CharacterDefinition = buildFighterCharacter({
  id: KUNOICHI_CHARACTER_ID,
  label: 'Kunoichi',
  assetRoot: '/assets/kunoichi',
  anchorUsage: 'kunoichi ninja west-facing high-fidelity anchor',
  frameWidth: 320,
  actions: KUNOICHI_ACTIONS
});
