import type { CharacterDefinition } from './hero';
import { buildFighterCharacter, rect, type FighterActionSpec } from './fighterCharacter';

// Generated by scripts/sprites/character.py from scripts/sprites/characters/monkey-king.json.
// defaultVisual comes from the packed sheets, width-capped so the hurtbox follows the
// body rather than the weapon (visualWidthCap / visualFrom in the manifest). Attack boxes
// are measured from what sticks out in front of the body on the strike frames; guard
// boxes are copied from the shipped fighters. Tune by hand after playtesting.

export const MONKEY_KING_CHARACTER_ID = 'monkey-king';

const MONKEY_KING_ACTIONS: FighterActionSpec[] = [
  {
    action: 'idle',
    label: 'Idle',
    file: 'idle.png',
    frames: 6,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(129, 24, 120, 204)
  },
  {
    action: 'walk-forward',
    label: 'Walk Forward',
    file: 'walk-forward.png',
    frames: 6,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(129, 28, 120, 200)
  },
  {
    action: 'walk-backward',
    label: 'Walk Backward',
    file: 'walk-backward.png',
    frames: 6,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(129, 28, 120, 200)
  },
  {
    action: 'crouch',
    label: 'Crouch',
    file: 'crouch.png',
    frames: 6,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(129, 30, 120, 198)
  },
  {
    action: 'jump',
    label: 'Jump',
    file: 'jump.png',
    frames: 6,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(129, 34, 120, 194)
  },
  {
    action: 'block-high',
    label: 'Block High',
    file: 'block-high.png',
    frames: 6,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(129, 26, 120, 203),
    guard: rect(124, 44, 136, 116)
  },
  {
    action: 'block-low',
    label: 'Block Low',
    file: 'block-low.png',
    frames: 6,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(129, 24, 120, 204),
    guard: rect(124, 110, 136, 120)
  },
  {
    action: 'hit-high',
    label: 'Hit High',
    file: 'hit-high.png',
    frames: 6,
    frameRate: 12,
    repeat: 0,
    defaultVisual: rect(129, 25, 120, 203)
  },
  {
    action: 'light-punch',
    label: 'Staff Jab',
    file: 'light-punch.png',
    frames: 6,
    frameRate: 14,
    repeat: 0,
    defaultVisual: rect(114, 32, 150, 196),
    attack: { frames: [2, 3], bounds: rect(52, 69, 70, 59) }
  },
  {
    action: 'heavy-kick',
    label: 'Tail Sweep',
    file: 'heavy-kick.png',
    frames: 6,
    frameRate: 12,
    repeat: 0,
    defaultVisual: rect(104, 25, 170, 203),
    attack: { frames: [2, 3], bounds: rect(52, 100, 60, 112) }
  },
  {
    action: 'special-charge',
    label: 'Golden Eyes',
    file: 'special-charge.png',
    frames: 6,
    frameRate: 14,
    repeat: 0,
    defaultVisual: rect(129, 20, 120, 209)
  },
  {
    action: 'special',
    label: 'Thousand Staff Storm',
    file: 'special.png',
    frames: 9,
    frameRate: 16,
    repeat: 0,
    defaultVisual: rect(94, 11, 190, 217),
    attackSpans: [
      { frames: [2], bounds: rect(61, 60, 41, 167) },
      { frames: [4], bounds: rect(28, 62, 84, 76) },
      { frames: [6], bounds: rect(48, 48, 54, 119) }
    ]
  },
  {
    action: 'knockdown',
    label: 'Knockdown',
    file: 'knockdown.png',
    frames: 6,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(101, 150, 176, 71)
  }
];

export const MONKEY_KING_CHARACTER: CharacterDefinition = buildFighterCharacter({
  id: MONKEY_KING_CHARACTER_ID,
  label: 'Monkey King',
  assetRoot: '/assets/monkey-king',
  anchorUsage: 'monkey-king west-facing high-fidelity anchor',
  frameWidth: 384,
  actions: MONKEY_KING_ACTIONS
});
