import type { CharacterDefinition } from './hero';
import { buildFighterCharacter, rect, type FighterActionSpec } from './fighterCharacter';

// Generated by scripts/sprites/character.py from scripts/sprites/characters/muay-thai.json.
// defaultVisual comes from the packed sheets, width-capped so the hurtbox follows the
// body rather than the weapon (visualWidthCap / visualFrom in the manifest). Attack boxes
// are measured from what sticks out in front of the body on the strike frames; guard
// boxes are copied from the shipped fighters. Tune by hand after playtesting.

export const MUAY_THAI_CHARACTER_ID = 'muay-thai';

const MUAY_THAI_ACTIONS: FighterActionSpec[] = [
  {
    action: 'idle',
    label: 'Idle',
    file: 'idle.png',
    frames: 6,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(105, 20, 118, 208)
  },
  {
    action: 'walk-forward',
    label: 'Walk Forward',
    file: 'walk-forward.png',
    frames: 6,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(103, 28, 109, 201)
  },
  {
    action: 'walk-backward',
    label: 'Walk Backward',
    file: 'walk-backward.png',
    frames: 6,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(103, 27, 109, 201)
  },
  {
    action: 'crouch',
    label: 'Crouch',
    file: 'crouch.png',
    frames: 6,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(103, 78, 108, 151)
  },
  {
    action: 'jump',
    label: 'Jump',
    file: 'jump.png',
    frames: 5,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(106, 25, 110, 206)
  },
  {
    action: 'block-high',
    label: 'Block High',
    file: 'block-high.png',
    frames: 3,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(111, 28, 104, 200),
    guard: rect(92, 44, 136, 116)
  },
  {
    action: 'block-low',
    label: 'Block Low',
    file: 'block-low.png',
    frames: 6,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(101, 72, 113, 156),
    guard: rect(92, 110, 136, 120)
  },
  {
    action: 'hit-high',
    label: 'Hit High',
    file: 'hit-high.png',
    frames: 6,
    frameRate: 12,
    repeat: 0,
    defaultVisual: rect(104, 37, 117, 192)
  },
  {
    action: 'light-punch',
    label: 'Jab Elbow',
    file: 'light-punch.png',
    frames: 5,
    frameRate: 14,
    repeat: 0,
    defaultVisual: rect(87, 32, 140, 196),
    attack: { frames: [2, 3], bounds: rect(56, 46, 52, 64) }
  },
  {
    action: 'heavy-kick',
    label: 'Low Kick',
    file: 'heavy-kick.png',
    frames: 5,
    frameRate: 12,
    repeat: 0,
    defaultVisual: rect(66, 37, 154, 191),
    attack: { frames: [2, 3], bounds: rect(52, 96, 80, 86) }
  },
  {
    action: 'special-charge',
    label: 'Wai Kru',
    file: 'special-charge.png',
    frames: 8,
    frameRate: 14,
    repeat: 0,
    defaultVisual: rect(97, 22, 120, 206)
  },
  {
    action: 'special',
    label: 'Eight Limbs Fury',
    file: 'special.png',
    frames: 8,
    frameRate: 16,
    repeat: 0,
    defaultVisual: rect(69, 15, 156, 214),
    attackSpans: [
      { frames: [2], bounds: rect(38, 60, 116, 100) },
      { frames: [4], bounds: rect(38, 60, 116, 100) },
      { frames: [6], bounds: rect(56, 52, 76, 150) }
    ]
  },
  {
    action: 'knockdown',
    label: 'Knockdown',
    file: 'knockdown.png',
    frames: 7,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(69, 177, 176, 52)
  }
];

export const MUAY_THAI_CHARACTER: CharacterDefinition = buildFighterCharacter({
  id: MUAY_THAI_CHARACTER_ID,
  label: 'Muay Thai',
  assetRoot: '/assets/muay-thai',
  anchorUsage: 'muay-thai west-facing high-fidelity anchor',
  frameWidth: 320,
  actions: MUAY_THAI_ACTIONS
});
