import type { CharacterDefinition } from './hero';
import { buildFighterCharacter, rect, type FighterActionSpec } from './fighterCharacter';

// Generated by scripts/sprites/character.py from scripts/sprites/characters/shaolin-monk.json.
// defaultVisual comes from the packed sheets, width-capped so the hurtbox follows the
// body rather than the weapon (visualWidthCap / visualFrom in the manifest). Attack boxes
// are measured from what sticks out in front of the body on the strike frames; guard
// boxes are copied from the shipped fighters. Tune by hand after playtesting.

export const SHAOLIN_MONK_CHARACTER_ID = 'shaolin-monk';

const SHAOLIN_MONK_ACTIONS: FighterActionSpec[] = [
  {
    action: 'idle',
    label: 'Idle',
    file: 'idle.png',
    frames: 6,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(129, 30, 120, 199)
  },
  {
    action: 'walk-forward',
    label: 'Walk Forward',
    file: 'walk-forward.png',
    frames: 7,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(129, 28, 120, 200)
  },
  {
    action: 'walk-backward',
    label: 'Walk Backward',
    file: 'walk-backward.png',
    frames: 6,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(129, 28, 120, 201)
  },
  {
    action: 'crouch',
    label: 'Crouch',
    file: 'crouch.png',
    frames: 7,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(129, 68, 120, 160)
  },
  {
    action: 'jump',
    label: 'Jump',
    file: 'jump.png',
    frames: 7,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(129, 24, 120, 210)
  },
  {
    action: 'block-high',
    label: 'Block High',
    file: 'block-high.png',
    frames: 7,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(129, 24, 120, 205),
    guard: rect(124, 44, 136, 116)
  },
  {
    action: 'block-low',
    label: 'Block Low',
    file: 'block-low.png',
    frames: 4,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(129, 50, 120, 179),
    guard: rect(124, 110, 136, 120)
  },
  {
    action: 'hit-high',
    label: 'Hit High',
    file: 'hit-high.png',
    frames: 7,
    frameRate: 12,
    repeat: 0,
    defaultVisual: rect(129, 34, 120, 194)
  },
  {
    action: 'light-punch',
    label: 'Palm Strike',
    file: 'light-punch.png',
    frames: 7,
    frameRate: 14,
    repeat: 0,
    defaultVisual: rect(119, 19, 140, 211),
    attack: { frames: [2, 3, 4], bounds: rect(88, 46, 64, 50) }
  },
  {
    action: 'heavy-kick',
    label: 'Sweep Kick',
    file: 'heavy-kick.png',
    frames: 6,
    frameRate: 12,
    repeat: 0,
    defaultVisual: rect(109, 40, 160, 188),
    attack: { frames: [2, 3], bounds: rect(14, 121, 103, 95) }
  },
  {
    action: 'special-charge',
    label: 'Inner Fire',
    file: 'special-charge.png',
    frames: 7,
    frameRate: 14,
    repeat: 0,
    defaultVisual: rect(129, 2, 120, 227)
  },
  {
    action: 'special',
    label: 'Burning Palm',
    file: 'special.png',
    frames: 8,
    frameRate: 16,
    repeat: 0,
    defaultVisual: rect(99, 10, 180, 220),
    attackSpans: [
      { frames: [2], bounds: rect(69, 28, 38, 70) },
      { frames: [4], bounds: rect(70, 60, 116, 100) },
      { frames: [6], bounds: rect(21, 22, 86, 146) }
    ]
  },
  {
    action: 'knockdown',
    label: 'Knockdown',
    file: 'knockdown.png',
    frames: 7,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(101, 155, 176, 72)
  }
];

export const SHAOLIN_MONK_CHARACTER: CharacterDefinition = buildFighterCharacter({
  id: SHAOLIN_MONK_CHARACTER_ID,
  label: 'Shaolin Monk',
  assetRoot: '/assets/shaolin-monk',
  anchorUsage: 'shaolin-monk west-facing high-fidelity anchor',
  frameWidth: 384,
  actions: SHAOLIN_MONK_ACTIONS
});
