import type { CharacterDefinition } from './hero';
import { buildFighterCharacter, rect, type FighterActionSpec } from './fighterCharacter';

// Generated by scripts/sprites/character.py from scripts/sprites/characters/viking-berserker.json.
// defaultVisual comes from the packed sheets, width-capped so the hurtbox follows the
// body rather than the weapon (visualWidthCap / visualFrom in the manifest). Attack boxes
// are measured from what sticks out in front of the body on the strike frames; guard
// boxes are copied from the shipped fighters. Tune by hand after playtesting.

export const VIKING_BERSERKER_CHARACTER_ID = 'viking-berserker';

const VIKING_BERSERKER_ACTIONS: FighterActionSpec[] = [
  {
    action: 'idle',
    label: 'Idle',
    file: 'idle.png',
    frames: 8,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(107, 29, 132, 199)
  },
  {
    action: 'walk-forward',
    label: 'Walk Forward',
    file: 'walk-forward.png',
    frames: 7,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(107, 26, 132, 203)
  },
  {
    action: 'walk-backward',
    label: 'Walk Backward',
    file: 'walk-backward.png',
    frames: 6,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(107, 25, 132, 203)
  },
  {
    action: 'crouch',
    label: 'Crouch',
    file: 'crouch.png',
    frames: 4,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(107, 63, 132, 165)
  },
  {
    action: 'jump',
    label: 'Jump',
    file: 'jump.png',
    frames: 6,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(107, 23, 132, 207)
  },
  {
    action: 'block-high',
    label: 'Block High',
    file: 'block-high.png',
    frames: 4,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(107, 23, 132, 205),
    guard: rect(108, 44, 136, 116)
  },
  {
    action: 'block-low',
    label: 'Block Low',
    file: 'block-low.png',
    frames: 4,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(107, 45, 132, 183),
    guard: rect(108, 110, 136, 120)
  },
  {
    action: 'hit-high',
    label: 'Hit High',
    file: 'hit-high.png',
    frames: 4,
    frameRate: 12,
    repeat: 0,
    defaultVisual: rect(107, 27, 132, 201)
  },
  {
    action: 'light-punch',
    label: 'Light Attack',
    file: 'light-punch.png',
    frames: 6,
    frameRate: 14,
    repeat: 0,
    defaultVisual: rect(98, 22, 150, 207),
    attack: { frames: [2, 3], bounds: rect(35, 34, 71, 148) }
  },
  {
    action: 'heavy-punch',
    label: 'Heavy Chop',
    file: 'heavy-punch.png',
    frames: 6,
    frameRate: 12,
    repeat: 0,
    defaultVisual: rect(93, 17, 160, 212),
    attack: { frames: [3, 4], bounds: rect(24, 42, 77, 149) }
  },
  {
    action: 'special-charge',
    label: 'Storm Charge',
    file: 'special-charge.png',
    frames: 4,
    frameRate: 14,
    repeat: 0,
    defaultVisual: rect(107, 27, 132, 201)
  },
  {
    action: 'special',
    label: 'Storm Whirlwind',
    file: 'special.png',
    frames: 9,
    frameRate: 16,
    repeat: 0,
    defaultVisual: rect(81, 32, 184, 198),
    attackSpans: [
      { frames: [2], bounds: rect(30, 95, 59, 71) },
      { frames: [4], bounds: rect(36, 66, 53, 75) },
      { frames: [6], bounds: rect(28, 67, 61, 162) }
    ]
  },
  {
    action: 'knockdown',
    label: 'Knockdown',
    file: 'knockdown.png',
    frames: 6,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(85, 149, 176, 80)
  }
];

export const VIKING_BERSERKER_CHARACTER: CharacterDefinition = buildFighterCharacter({
  id: VIKING_BERSERKER_CHARACTER_ID,
  label: 'Viking Berserker',
  assetRoot: '/assets/viking-berserker',
  anchorUsage: 'viking berserker west-facing high-fidelity anchor',
  frameWidth: 352,
  actions: VIKING_BERSERKER_ACTIONS
});
