import type { CharacterDefinition } from './hero';
import { buildFighterCharacter, rect, type FighterActionSpec } from './fighterCharacter';

// Generated by scripts/sprites/character.py from scripts/sprites/characters/wudang-swordswoman.json.
// defaultVisual comes from the packed sheets, width-capped so the hurtbox follows the
// body rather than the weapon (visualWidthCap / visualFrom in the manifest). Attack boxes
// are measured from what sticks out in front of the body on the strike frames; guard
// boxes are copied from the shipped fighters. Tune by hand after playtesting.

export const WUDANG_SWORDSWOMAN_CHARACTER_ID = 'wudang-swordswoman';

const WUDANG_SWORDSWOMAN_ACTIONS: FighterActionSpec[] = [
  {
    action: 'idle',
    label: 'Idle',
    file: 'idle.png',
    frames: 6,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(129, 30, 120, 199)
  },
  {
    action: 'walk-forward',
    label: 'Walk Forward',
    file: 'walk-forward.png',
    frames: 6,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(129, 21, 120, 208)
  },
  {
    action: 'walk-backward',
    label: 'Walk Backward',
    file: 'walk-backward.png',
    frames: 6,
    frameRate: 8,
    repeat: -1,
    defaultVisual: rect(129, 20, 120, 209)
  },
  {
    action: 'crouch',
    label: 'Crouch',
    file: 'crouch.png',
    frames: 6,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(129, 59, 120, 170)
  },
  {
    action: 'jump',
    label: 'Jump',
    file: 'jump.png',
    frames: 6,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(129, 35, 120, 194)
  },
  {
    action: 'block-high',
    label: 'Block High',
    file: 'block-high.png',
    frames: 2,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(129, 32, 120, 196),
    guard: rect(124, 44, 136, 116)
  },
  {
    action: 'block-low',
    label: 'Block Low',
    file: 'block-low.png',
    frames: 6,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(129, 59, 120, 169),
    guard: rect(124, 110, 136, 120)
  },
  {
    action: 'hit-high',
    label: 'Hit High',
    file: 'hit-high.png',
    frames: 6,
    frameRate: 12,
    repeat: 0,
    defaultVisual: rect(129, 31, 120, 198)
  },
  {
    action: 'light-punch',
    label: 'Swift Thrust',
    file: 'light-punch.png',
    frames: 6,
    frameRate: 14,
    repeat: 0,
    defaultVisual: rect(114, 32, 150, 197),
    attack: { frames: [2, 3], bounds: rect(45, 91, 77, 50) }
  },
  {
    action: 'heavy-kick',
    label: 'Low Sweep Cut',
    file: 'heavy-kick.png',
    frames: 6,
    frameRate: 12,
    repeat: 0,
    defaultVisual: rect(104, 25, 170, 204),
    attack: { frames: [2, 3], bounds: rect(58, 145, 54, 73) }
  },
  {
    action: 'special-charge',
    label: 'Cloud Breath',
    file: 'special-charge.png',
    frames: 6,
    frameRate: 14,
    repeat: 0,
    defaultVisual: rect(129, 26, 120, 203)
  },
  {
    action: 'special',
    label: 'Cloud Hand Sword',
    file: 'special.png',
    frames: 9,
    frameRate: 16,
    repeat: 0,
    defaultVisual: rect(94, 18, 190, 211),
    attackSpans: [
      { frames: [2], bounds: rect(40, 108, 84, 56) },
      { frames: [4], bounds: rect(30, 120, 92, 70) },
      { frames: [6], bounds: rect(30, 110, 92, 90) }
    ]
  },
  {
    action: 'knockdown',
    label: 'Knockdown',
    file: 'knockdown.png',
    frames: 5,
    frameRate: 10,
    repeat: 0,
    defaultVisual: rect(101, 127, 176, 102)
  }
];

export const WUDANG_SWORDSWOMAN_CHARACTER: CharacterDefinition = buildFighterCharacter({
  id: WUDANG_SWORDSWOMAN_CHARACTER_ID,
  label: 'Wudang Swordswoman',
  assetRoot: '/assets/wudang-swordswoman',
  anchorUsage: 'wudang-swordswoman west-facing high-fidelity anchor',
  frameWidth: 384,
  actions: WUDANG_SWORDSWOMAN_ACTIONS
});
